import { Creature, Trade } from '@/lib/types';

export const initialTrades: Trade[] = [];

export const initialCreatures: Creature[] = [
    { id: '1', name: 'Sombra', description: 'Una descripción de Sombra...', imageUrl: null, encounters: [] },
    { id: '2', name: 'Slimes', description: 'Una descripción de Slimes...', imageUrl: null, encounters: [] },
    { id: '3', name: 'Goblins', description: 'Una descripción de Goblins...', imageUrl: null, encounters: [] },
    { id: '4', name: 'Trolls', description: 'Una descripción de Trolls...', imageUrl: null, encounters: [] },
    { id: '5', name: 'Orcos', description: 'Una descripción de Orcos...', imageUrl: null, encounters: [] },
    { id: '6', name: 'Minotauros', description: 'Una descripción de Minotauros...', imageUrl: null, encounters: [] },
    { id: '7', name: 'Mujeres Lizzards', description: 'Una descripción de Mujeres Lizzards...', imageUrl: null, encounters: [] },
    { id: '8', name: 'Hombres Lobos', description: 'Una descripción de Hombres Lobos...', imageUrl: null, encounters: [] },
    { id: '9', name: 'Faunos', description: 'Una descripción de Faunos...', imageUrl: null, encounters: [] },
    { id: '10', name: 'Sirenas', description: 'Una descripción de Sirenas...', imageUrl: null, encounters: [] },
    { id: '11', name: 'Hadas', description: 'Una descripción de Hadas...', imageUrl: null, encounters: [] },
    { id: '12', name: 'Fenix', description: 'Una descripción de Fenix...', imageUrl: null, encounters: [] },
    { id: '13', name: 'Basilisco', description: 'Una descripción de Basilisco...', imageUrl: null, encounters: [] },
    { id: '14', name: 'Kraken', description: 'Una descripción de Kraken...', imageUrl: null, encounters: [] },
    { id: '15', name: 'Leviatan', description: 'Una descripción de Leviatan...', imageUrl: null, encounters: [] },
    { id: '16', name: 'Cthulhu', description: 'Una descripción de Cthulhu...', imageUrl: null, encounters: [] },
    { id: '17', name: 'Un Dragón Ancestral', description: 'Una descripción de Un Dragón Ancestral...', imageUrl: null, encounters: [] },
];

export const currencyPairs = [
  { label: "EUR/USD", value: "EUR/USD" },
  { label: "GBP/USD", value: "GBP/USD" },
  { label: "AUD/USD", value: "AUD/USD" },
  { label: "NZD/USD", value: "NZD/USD" },
  { label: "USD/JPY", value: "USD/JPY" },
  { label: "USD/CHF", value: "USD/CHF" },
  { label: "USD/CAD", value: "USD/CAD" },
  { label: "EUR/GBP", value: "EUR/GBP" },
  { label: "EUR/JPY", value: "EUR/JPY" },
  { label: "EUR/AUD", value: "EUR/AUD" },
  { label: "EUR/NZD", value: "EUR/NZD" },
  { label: "EUR/CAD", value: "EUR/CAD" },
  { label: "EUR/CHF", value: "EUR/CHF" },
  { label: "GBP/JPY", value: "GBP/JPY" },
  { label: "GBP/AUD", value: "GBP/AUD" },
  { label: "GBP/NZD", value: "GBP/NZD" },
  { label: "GBP/CAD", value: "GBP/CAD" },
  { label: "GBP/CHF", value: "GBP/CHF" },
  { label: "AUD/JPY", value: "AUD/JPY" },
  { label: "AUD/NZD", value: "AUD/NZD" },
  { label: "AUD/CAD", value: "AUD/CAD" },
  { label: "AUD/CHF", value: "AUD/CHF" },
  { label: "NZD/JPY", value: "NZD/JPY" },
  { label: "NZD/CAD", value: "NZD/CAD" },
  { label: "NZD/CHF", value: "NZD/CHF" },
  { label: "CAD/JPY", value: "CAD/JPY" },
  { label: "CAD/CHF", value: "CAD/CHF" },
  { label: "CHF/JPY", value: "CHF/JPY" },
  { label: "USD/NOK", value: "USD/NOK" },
  { label: "USD/SEK", value: "USD/SEK" },
  { label: "USD/DKK", value: "USD/DKK" },
  { label: "USD/MXN", value: "USD/MXN" },
  { label: "USD/ZAR", value: "USD/ZAR" },
  { label: "USD/HKD", value: "USD/HKD" },
  { label: "USD/SGD", value: "USD/SGD" },
  { label: "USD/TRY", value: "USD/TRY" },
  { label: "USD/PLN", value: "USD/PLN" },
  { label: "USD/CNH", value: "USD/CNH" },
  { label: "EUR/NOK", value: "EUR/NOK" },
  { label: "EUR/SEK", value: "EUR/SEK" },
  { label: "EUR/DKK", value: "EUR/DKK" },
  { label: "EUR/TRY", value: "EUR/TRY" },
  { label: "EUR/PLN", value: "EUR/PLN" },
  { label: "EUR/HUF", value: "EUR/HUF" },
  { label: "EUR/CZK", value: "EUR/CZK" },
  { label: "GBP/NOK", value: "GBP/NOK" },
  { label: "GBP/SEK", value: "GBP/SEK" },
];

  