import { Trade } from '@/lib/types';

export const initialTrades: Trade[] = [
  { id: '1', pair: 'EUR/GBP', status: 'win', pips: 44, lotSize: 0.1, profit: 220, date: '2024-03-27T10:00:00Z', strategy: '3G', strategyColor: 'rgb(4, 120, 87)', notes: 'Buena entrada siguiendo la tendencia principal.' },
  { id: '2', pair: 'USD/JPY', status: 'win', pips: 32, lotSize: 0.1, profit: 160, date: '2024-03-26T10:00:00Z', strategy: '1G', strategyColor: 'rgb(16, 185, 129)', notes: 'Confirmación con patrón de velas.' },
  { id: '3', pair: 'GBP/CHF', status: 'loss', pips: -19, lotSize: 0.05, profit: -95, date: '2024-03-25T10:00:00Z', strategy: '2C', strategyColor: 'rgb(29, 78, 216)', notes: 'Entrada precipitada, el mercado se giró.' },
  { id: '4', pair: 'EUR/USD', status: 'win', pips: 42, lotSize: 0.2, profit: 280, date: '2024-03-24T10:00:00Z', strategy: '5G', strategyColor: 'rgb(6, 78, 59)' },
  { id: '5', pair: 'USD/CAD', status: 'loss', pips: -15, lotSize: 0.05, profit: -75, date: '2024-03-09T10:00:00Z', strategy: '1C', strategyColor: 'rgb(59, 130, 246)' },
  { id: '6', pair: 'AUD/JPY', status: 'win', pips: 38, lotSize: 0.1, profit: 190, date: '2024-03-06T10:00:00Z', strategy: '4G', strategyColor: 'rgb(6, 95, 70)', notes: 'Operación a favor de la tendencia semanal.' },
  { id: '7', pair: 'GBP/USD', status: 'loss', pips: -22, lotSize: 0.1, profit: -110, date: '2024-03-03T10:00:00Z', strategy: '3C', strategyColor: 'rgb(220, 38, 38)' },
  { id: '8', pair: 'EUR/JPY', status: 'win', pips: 28, lotSize: 0.1, profit: 140, date: '2024-02-29T10:00:00Z', strategy: '2C', strategyColor: 'rgb(29, 78, 216)' },
  { id: '9', pair: 'USD/CHF', status: 'win', pips: 50, lotSize: 0.2, profit: 320, date: '2024-02-11T10:00:00Z', strategy: '1G', strategyColor: 'rgb(16, 185, 129)' },
  { id: '10', pair: 'GBP/JPY', status: 'loss', pips: -12, lotSize: 0.05, profit: -60, date: '2024-02-07T10:00:00Z', strategy: '4C', strategyColor: 'rgb(30, 58, 138)', notes: 'Stop loss ajustado demasiado pronto.' }
];

export const currencyPairs = [
  { label: "EUR/USD", value: "EUR/USD" },
  { label: "GBP/USD", value: "GBP/USD" },
  { label: "AUD/USD", value: "AUD/USD" },
  { label: "NZD/USD", value: "NZD/USD" },
  { label: "USD/JPY", value: "USD/JPY" },
  { label: "USD/CHF", value: "USD/CHF" },
  { label: "USD/CAD", value: "USD/CAD" },
  { label: "EUR/GBP", value: "EUR/GBP" },
  { label: "EUR/JPY", value: "EUR/JPY" },
  { label: "EUR/AUD", value: "EUR/AUD" },
  { label: "EUR/NZD", value: "EUR/NZD" },
  { label: "EUR/CAD", value: "EUR/CAD" },
  { label: "EUR/CHF", value: "EUR/CHF" },
  { label: "GBP/JPY", value: "GBP/JPY" },
  { label: "GBP/AUD", value: "GBP/AUD" },
  { label: "GBP/NZD", value: "GBP/NZD" },
  { label: "GBP/CAD", value: "GBP/CAD" },
  { label: "GBP/CHF", value: "GBP/CHF" },
  { label: "AUD/JPY", value: "AUD/JPY" },
  { label: "AUD/NZD", value: "AUD/NZD" },
  { label: "AUD/CAD", value: "AUD/CAD" },
  { label: "AUD/CHF", value: "AUD/CHF" },
  { label: "NZD/JPY", value: "NZD/JPY" },
  { label: "NZD/CAD", value: "NZD/CAD" },
  { label: "NZD/CHF", value: "NZD/CHF" },
  { label: "CAD/JPY", value: "CAD/JPY" },
  { label: "CAD/CHF", value: "CAD/CHF" },
  { label: "CHF/JPY", value: "CHF/JPY" },
  { label: "USD/NOK", value: "USD/NOK" },
  { label: "USD/SEK", value: "USD/SEK" },
  { label: "USD/DKK", value: "USD/DKK" },
  { label: "USD/MXN", value: "USD/MXN" },
  { label: "USD/ZAR", value: "USD/ZAR" },
  { label: "USD/HKD", value: "USD/HKD" },
  { label: "USD/SGD", value: "USD/SGD" },
  { label: "USD/TRY", value: "USD/TRY" },
  { label: "USD/PLN", value: "USD/PLN" },
  { label: "USD/CNH", value: "USD/CNH" },
  { label: "EUR/NOK", value: "EUR/NOK" },
  { label: "EUR/SEK", value: "EUR/SEK" },
  { label: "EUR/DKK", value: "EUR/DKK" },
  { label: "EUR/TRY", value: "EUR/TRY" },
  { label: "EUR/PLN", value: "EUR/PLN" },
  { label: "EUR/HUF", value: "EUR/HUF" },
  { label: "EUR/CZK", value: "EUR/CZK" },
  { label: "GBP/NOK", value: "GBP/NOK" },
  { label: "GBP/SEK", value: "GBP/SEK" },
];
